language: node_js
node_js:
- '0.10'
notifications:
  hipchat:
    rooms:
      secure: HZrZlpzPhZYTtYoTjrBfIQx4oz75ShJ+WxerEsBJ4EQihvLePxWpf2G+LDAvJPoATHbOnuwGuw+9qCPiqu2LrtWb/eOFN41rN5rZV1qw+ogg9G7VzgGtvYwK0wEbAfSeKmmvuAbOxNKDPoimpIBx18renm09aG+FbXn5tNaL/KM=
