language: node_js
node_js:
- '0.10'
notifications:
  hipchat:
    rooms:
      secure: HCzm7QnWJAu5SFJyVTG4TqURwJ3JRizGeqy/mVhXB5YdyL5RURf3rTUWeQb0ZQMr5EDR8YNaOv8jDtF5o2TGpE0g4HjS19ANTEGYJAX7VrM+rr9H6WNNDjOk09JpfKUTdaTCUI0xKNs6WHWO9O1SmhKS014Psd7NuYHTkhl2m1o=
